### ISSUE TITLE
Question about vob emb file

### ISSUE THREAD

**Issue by zys133zys133** [Websail-NU/adaptive_lm#17]
Hi Thanapon Noraset,

This is Zheng Yuan, a Phd student from Doug Downey's group in Northwestern EECS department.

A questions for: https://github.com/Websail-NU/adaptive_lm/blob/master/train.py#L41

Each line in emb_vob file seems like a tuple of a word and its count. So, where is the code that convert the words to the embedding vectors?

LOL,
Zheng

**Comment by northanapon** [comment]
LOL, you don't need to introduce yourself.

`data_utils.Vocabulary.from_vocab_file(file_path)` can read from a file without the count. It will assume that the count is zero.

The  embedding vocab is used when we already have a pre-trained embedding set. In a normal setting of training a language model, we don't need this. I'll simplify the training code.

**Comment by zys133zys133** [comment]
Aha, introduce myself is my joke.
OK. So it means that in this version of code, the word representation is just an integer ID for each word?

**Comment by northanapon** [comment]
It means that you can ignore them as long as `--shared_emb_lm_logit` is `False` (default).

**Comment by northanapon** [comment]
@yu71941628 and @Ettrai

You can take a look at https://github.com/Websail-NU/adaptive_lm/tree/simple-lm.
